name: "Mirroring Repository"
description: "Push commits to another repository on GitHub, GitLab, BitBucket, AWS CodeCommit, etc."
branding:
  icon: "archive"
  color: "blue"
inputs:
  ssh_private_key:
    description: "SSH private key for ssh connection to the target repository"
    required: false
  target_repo_url:
    description: "Target url"
    required: true
  ssh_username:
    description: "Username for ssh connection"
    required: false
    default: "git"
  target_branch:
    description: "name of target branch"
    require: true
runs:
  using: 'docker'
  image: 'Dockerfile'
